import mysql.connector

mydb=mysql.connector.connect(

	host="localhost",

	user="root",

	passwd="",

	database="geo_data"
	)

mycursor=mydb.cursor()



districts=["Arusha Region",
                "Meru District",
                "Arusha City",
                "Arusha District",
                "Karatu District",
                "Longido District",
                "Monduli District",
                "Ngorongoro District",
                "Dar es Salaam Region",
                "Ilala Municipal",
                "Kinondoni Municipal",
                "Temeke Municipal",
                "Kigamboni Municipal",
                "Ubungo Municipal",
                "Dodoma Region",
                "Bahi District",
                "Chamwino District",
                "Chemba District",
                "Dodoma Municipal",
                "Kondoa District",
                "Kongwa District",
                "Mpwapwa District",
                "Geita Region",
                "Bukombe District",
                "Chato District",
                "Geita Town",
                "Mbogwe District",
                "Nyang'hwale District",
                "Iringa Region",
                "Iringa District",
                "Iringa Municipal",
                "Kilolo District",
                "Mafinga Town",
                "Mufindi District",
                "Kagera Region",
                "Biharamulo District",
                "Bukoba District",
                "Bukoba Municipal",
                "Karagwe District",
                "Kyerwa District",
                "Missenyi District",
                "Muleba District",
                "Ngara District",
                "Katavi Region",
                "Mlele District",
                "Mpanda District",
                "Mpanda Town",
                "Kigoma Region",
                "Buhigwe District",
                "Kakonko District",
                "Kasulu District",
                "Kasulu Town",
                "Kibondo District",
                "Kigoma District",
                "Kigoma-Ujiji Municipal",
                "Uvinza District",
                "Kilimanjaro Region",
                "Hai District",
                "Moshi District",
                "Moshi Municipal",
                "Mwanga District",
                "Rombo District",
                "Same District",
                "Siha District",
                "Pemba Kusini Region",
                "Chake Chake District",
                "Mkoani District",
                "Unguja Kusini Region",
                "Kati District",
                "Kusini District",
                "Lindi Region",
                "Kilwa District",
                "Lindi District",
                "Lindi Municipal",
                "Liwale District",
                "Nachingwea District",
                "Ruangwa District",
                "Manyara Region",
                "Babati Town",
                "Babati District",
                "Hanang District",
                "Kiteto District",
                "Mbulu District",
                "Simanjiro District",
                "Mara Region",
                "Bunda District",
                "Butiama District",
                "Musoma District",
                "Musoma Municipal",
                "Rorya District",
                "Serengeti District",
                "Tarime District",
                "Mbeya Region",
                "Busokelo District",
                "Chunya District",
                "Kyela District",
                "Mbarali City",
                "Mbeya District",
                "Mbeya District",
                "Rungwe",
                "Unguja Mjini Magharibi Region",
                "Magharibi District",
                "Mjini District",
                "Morogoro Region",
                "Gairo District",
                "Kilombero District",
                "Kilosa District",
                "Morogoro District",
                "Morogoro Municipal",
                "Mvomero District",
                "Ulanga District",
                "Malinyi District",
                "Ifakara Township",
                "Mtwara Region",
                "Masasi District",
                "Masasi Town",
                "Mtwara District",
                "Mtwara Municipal",
                "Nanyumbu District",
                "Newala District",
                "Tandahimba District",
                "Mwanza Region",
                "Ilemela Municipal",
                "Kwimba District",
                "Magu District",
                "Misungwi District",
                "Nyamagana Municipal",
                "Sengerema District",
                "Ukerewe District",
                "Njombe Region",
                "Ludewa District",
                "Makambako Town",
                "Makete District",
                "Njombe District",
                "Njombe Town",
                "Wanging'ombe District",
                "Pwani Region",
                "Bagamoyo District",
                "Kibaha District",
                "Kibaha Town",
                "Kisarawe District",
                "Mafia District",
                "Mkuranga District",
                "Rufiji District",
                "Rukwa Region",
                "Kalambo District",
                "Nkasi District",
                "Sumbawanga District",
                "Sumbawanga Municipal",
                "Ruvuma Region",
                "Mbinga District",
                "Songea District",
                "Songea Municipal",
                "Tunduru District",
                "Namtumbo District",
                "Nyasa District",
                "Shinyanga Region",
                "Kahama Town",
                "Kahama District",
                "Kishapu District",
                "Shinyanga District",
                "Shinyanga Municipal",
                "Simiyu Region",
                "Bariadi District",
                "Busega District",
                "Itilima District",
                "Maswa District",
                "Meatu District",
                "Singida Region",
                "Ikungi District",
                "Iramba District",
                "Manyoni District",
                "Mkalama District",
                "Singida District",
                "Singida Municipal",
                "Songwe Region",
                "Ileje District",
                "Mbozi District",
                "Momba District",
                "Songwe District",
                "Tabora Region",
                "Igunga District",
                "Kaliua District",
                "Nzega District",
                "Sikonge District",
                "Tabora Municipal",
                "Urambo District",
                "Uyui District",
                "Tanga Region",
                "Handeni District",
                "Handeni Town",
                "Kilindi District",
                "Korogwe Town",
                "Korogwe District",
                "Lushoto District",
                "Muheza District",
                "Mkinga District",
                "Pangani District",
                "Tanga City",
                "Unguja Kaskazini Region",
                "Kaskazini A District",
                "Kaskazini B District",
                "Pemba Kusini Region",
                "Micheweni District",
                "Wete District",
                "Unguja Mjini Magharibi Region",
                "Unguja Magharibi District",
                "Unguja Mjini District"

]




z=0
for district in districts:
	if 'Region' in district :
		
		region=district.replace(" Region","")


		sql = "SELECT id FROM regions WHERE name = %s"
		val = (region, )

		mycursor.execute(sql, val)

		region = mycursor.fetchone()
		region=str(region)
		region=region.replace("(","")
		region=region.replace("),","")
		

	else:

		sql = "INSERT INTO districts (name, region_id) VALUES (%s, %s)"
		val = (district,region)	
		mycursor.execute(sql, val)
	
		mydb.commit()

	